### ISSUE TITLE
Constant offset of 1h in TPC and MV status box

### ISSUE THREAD

**Issue by l-althueser** [coderdj/emo#12]
On my system (mobile and laptop) I see an offset of 1h in the status of the runs. I have tried different browsers and machines - this seems to be connected to my account(?)

`Time: 01:01` should be `Time: 00:01` and `Time: 05:35` is `Time: 04:35`
![emo_issue](https://cloud.githubusercontent.com/assets/13698969/20886365/0420308a-baf6-11e6-845d-a8d42cd9ea4b.jpg)

**Comment by coderdj** [comment]
Closed in 5cda01496487064c73bd63c8b36cc87d13c7b23a. At least until next time change.

**Comment by coderdj** [comment]
Reopening myself. Apparently the fix only worked for chromium in Linux. Will look again.

**Comment by tunnell** [comment]
Can test in Chrome and Safari on Mac.


From: Daniel Coderre <notifications@github.com> <notifications@github.com>
Reply: coderdj/emo
<reply@reply.github.com>
<reply@reply.github.com>
Date: 5 December 2016 at 11:33:44
To: coderdj/emo <emo@noreply.github.com> <emo@noreply.github.com>
Subject:  Re: [coderdj/emo] Constant offset of 1h in TPC and MV status box
(#12)

Reopened #12 <https://github.com/coderdj/emo/issues/12>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/coderdj/emo/issues/12#event-882415745>, or mute the
thread

**Comment by coderdj** [comment]
Now closed. Tested in chromium, chrome, and edge.
