### ISSUE TITLE
glitches with updating the control screen? 

### ISSUE THREAD

**Issue by ghost** [coderdj/emo#22]
Hello
It seems to me that sometimes the updating of the daq control screen is not ok:
1) the graph sometimes does not appear for a long time, many tens of seconds up to a few minutes (image will be added). 
1.1) Even more annoying and misleading, it happens that the auto-update stops, so what you see refers to the past (I can make an image of this if needed).
2) Now the TPC is running, but it fails to show the related red button Iimage will be added).

Thanks
  DavidManyRequests Front
![daqnotupdating](https://cloud.githubusercontent.com/assets/24654713/21517474/31e9310c-cce8-11e6-9632-8b3537d98883.jpg)
![tpcrunningbutnoredbutton](https://cloud.githubusercontent.com/assets/24654713/21517570/d824af74-cce8-11e6-8d80-a481a64cf6f5.jpg)

**Comment by l-althueser** [comment]
Hi David,

Your first issue is known and no 'real' issue. From my experience this happens when you don't have enough network connect and/or the performance of the device is bad (e.g. tablet). The graph is loaded as tons of data points which allows to hover the mouse over each of it to get more information. 
A solution or workaround would be to not show 24h but 12h or less ;)

The second issue is also known and will be solved in the future ...

But this is only the experience of a former shifter :)

**Comment by ghost** [comment]
Hello Lutz

Thanks for your response, next time the problem happens, I will try to
change the time to shorter than the default 24 hours.

I suggest that as long as the shifter is supposed to use the tablet as a
tool to monitor the DAQ,
it is reasonable to expect that the main screen for this, the control
screen
will reliably update.

If changing the default period of this screen to a shorter time than 24
hours will cause it to work well,
that is OK.

But I do think that this issue is real.

Happy new year
  David

**Comment by ghost** [comment]
Hello

I agree with Lutz that the issue may be related to the combination of (weak) tablet and slow Internet,
yet, I guess that it should be possible to code the control screen to work well in these conditions. 

Details:
The issue with not filling the control screen is repeating on shifter2's tablet, with the Zurich apartment wifi.
As shown at the first image, only the runs show (now the TPC has no red button),
and the 'trigger status' template appears with no data.
Changing the options (data rate, 24 hours, 2 min bins) does not seem make any difference.
The Zurich apartment wifi download speed is about 1Mb/sec .
Other URLs and application get along with this low rate.
Also, the daq control screen works well on my laptop.
When using the cellular data, which is 17Mb/sec, the daq control screen works well on the tablet.

Happy new year
   David

**Comment by coderdj** [comment]
For 1. your internet is too slow. The ZRH apartment wifi is terrible, which is why the shifter tablets come with 4G. I tested this on 4G and it is fine. I'm not fixing this.

1.1 should be addressed with 9dd1e148338c9c57add09c10fa4e0f381af09d71. However I don't like this solution and would prefer shifters just update the page before interacting with it. 

2. is a known issue but I am unable to reproduce it. It did not happen before running with the muon veto so there's some specific order of starting the TPC/muon veto that causes it.

**Comment by coderdj** [comment]
This commit to kodiaq: fa28b74ce1fa76c22fb00a979f265bcd474f5abc should solve item 2. But it's a bit of a mess so I'm not sure if it will be 100% perfect.

Will close and reopen (or open new more specific issue) if still happens.

**Comment by ghost** [comment]
Hello Daniel

Thanks for taking care of the issues.

David
